services:
  postgrechalangesrv:
    image: 'postgres:17-alpine'
    container_name: postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      - 'POSTGRES_USER=challenge'
      - 'POSTGRES_PASSWORD=Senh@123'
      - 'POSTGRES_DB=challenge'
      - 'PGDATA=/var/lib/postgresql/data/pgdata'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 10s
      retries: 15
    volumes:
      - './chalange-database/data:/var/lib/postgresql/data'
      - './chalange-database/init-script:/docker-entrypoint-initdb.d/'
  bff:
    image: ${DOCKER_REGISTRY-}bff
    build:
      context: ./src/Backend
      dockerfile: Bff/Dockerfile
    depends_on:
      postgrechalangesrv:
        condition: service_healthy
    ports:  
      - '8080:8080'
    environment:
      - 'ASPNETCORE_ENVIRONMENT=Development'
      - 'ConnectionStrings__PostgresSqlConnectionString=Host=postgrechalangesrv;Port=5432;Username=challenge;Password=Senh@123;Database=challenge;Pooling=true;'
